export default [
    'react',
    'react-dom',
    'react-router',
    'mobx',
    'mobx-react',
    'fit-select',
    'validator',
    'fit-modal',
    'fit-render-to',
    'fit-message',
    'fit-tree',
    'fit-modal',
    'fit-message',
    'react-native',
    'lodash',
    'superagent',
]