// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/408129b4055668adf9fcb00b3efe1e6d38d43dd5/pure-render-decorator/pure-render-decorator.d.ts
declare module 'pure-render-decorator' {
  var PureRender: ClassDecorator;
  export = PureRender;
}
