///<reference path="../typings/index.d.ts" />
import './web-common/button/index'
import './web-common/tree/index'
import './web-common/tooltip/index'
import './web-common/margin-padding-editor/index'
import './common/image/index'
import './common/gif/index'
import './common/image-zoom/index'
import './common/image-viewer/index'
import './common/transmit-transparently/index'
import './common/auto-bind/index'
import './wefan/image/index'
import './wefan/resource-card/index'
import './wefan/navbar/index'
