// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/b20eb12c4c1f024689c4dbcb48ed8671695926c0/koa-mount/koa-mount.d.ts
declare module "koa-mount" {

    import * as Koa from "koa";

    interface Function { (ctx: Koa.Context, next?: () => any): any }

    function mount(app: Function): Function;

    function mount(app: Koa): Function;

    function mount(prefix: string, app: Function): Function;

    function mount(prefix: string, app: Koa): Function;

    namespace mount {}

    export = mount;
}
